FROM ocaml/opam2:alpine-3.12-ocaml-4.10 AS builder
WORKDIR /app
USER root
RUN apk update
RUN apk add \
  curl \
  git \
  m4 \
  musl-dev \
  libc-dev \
  postgresql-client \
  gmp-dev \
  pkgconfig \
  postgresql-dev \
  tree
RUN apk add perl linux-headers
RUN chown -R opam:opam .
USER opam
RUN opam init && opam update
COPY --chown=opam:opam opam.deps.sh .
RUN eval $(opam env) && opam switch && opam update && bash opam.deps.sh
COPY --chown=opam:opam . .
RUN eval $(opam env) && opam exec -- dune build --release bin/Agent.exe && \
  ./_build/default/bin/Agent.exe -help

FROM alpine:3.12
WORKDIR /app
COPY --from=builder /app/_build/default/bin/Agent.exe .
RUN apk upgrade --update && \
  apk add -U postgresql-client gmp-dev tzdata && \
  cp /usr/share/zoneinfo/Asia/Hong_Kong /etc/localtime && \
  rm -rf /var/cache/apk/*
CMD [ "Agent.exe" ]


