FROM ocaml/opam:alpine-3.14-ocaml-4.12-domains AS builder
WORKDIR /app
USER root
RUN apk update
RUN apk add \
  curl \
  git \
  m4 \
  musl-dev \
  libc-dev \
  postgresql-client \
  gmp-dev \
  pkgconfig \
  postgresql-dev \
  libev-dev \
  tree \
  tzdata \
  perl \
  linux-headers \
  && cp /usr/share/zoneinfo/Asia/Hong_Kong /etc/localtime \
  && rm -rf /var/cache/apk/*
RUN chown -R opam:opam .
USER opam
RUN opam init && opam update
COPY --chown=opam:opam opam.deps.sh .
RUN eval $(opam env) && opam switch && opam update && bash opam.deps.sh
COPY --chown=opam:opam . .
RUN eval $(opam env) && opam exec -- dune build --release bin/Agent.exe && \
  ./_build/default/bin/Agent.exe --help && \
  mv ./_build/default/bin/Agent.exe ./
CMD [ "./Agent.exe", "--poll-duration=60" ]
# FROM alpine:3.14
# WORKDIR /app


