{
 "title": "freshawair",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "AirScore",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(score) AS \"Grant\"\nFROM sensor_stats\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  sensor_index = '0'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(score) AS \"Malcom\"\nFROM sensor_stats\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  sensor_index = '1'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(co2) AS \"Grant\"\nFROM sensor_stats\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  sensor_index = '0'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(co2) AS \"Malcom\"\nFROM sensor_stats\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  sensor_index = '1'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "PM2.5 (3m moving avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  avg(pm25) OVER (ORDER BY \"timestamp\" ROWS 3 PRECEDING) AS \"pm25\"\nFROM sensor_stats\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  sensor_index = '0'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  avg(pm25) OVER (ORDER BY \"timestamp\" ROWS 3 PRECEDING) AS \"pm25\"\nFROM sensor_stats\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  sensor_index = '1'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Temp (F°)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  ((temp * 1.8) + 32) AS Grant\nFROM sensor_stats\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  sensor_index = '0'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  ((temp * 1.8) + 32) AS Malcom\nFROM sensor_stats\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  sensor_index = '1'\nORDER BY 1"
    }
   ]
  }
 ]
}